### ISSUE TITLE
Multiple sets

### ISSUE THREAD

**Issue by jenshenrik** [catnipped/SWDestinyProxy#1]
Doesn't seem to handle multiple sets (SoR), or maybe I'm just entering the wrong IDs? The json object don't seem to have an 'id' field, closest thing being 'position', but that looks like it's relative to the set.

**Comment by ryanvito** [comment]
I've added a quick little change after looking at the API and it works fine with multiple sets. I'll try to get the OP to take a pull request which will resolve the issue.

**Comment by ryanvito** [comment]
@jenshenrik The pull request was merged and now available. Please review and close this issue.
