### ISSUE TITLE
No pictures or symbols when printing

### ISSUE THREAD

**Issue by ryanvito** [catnipped/SWDestinyProxy#4]
When I go into print preview all the pictures and symbols disappear. Unfortunately it doesn't do me much good without them. I've been messing with it to see if maybe it is an issue with CSS but I am not having any luck.

**Comment by catnipped** [comment]
this is an issue with your browser. you have to make sure to ”print backgrounds” in your print settings

**Comment by ryanvito** [comment]
Thank you for the reply @canipped This was exactly my problem. I found the option and now it is working beautifully! Thank you!
